name: Building new Clang

on: [push]

env:
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing environment
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        docker rmi `docker images -q`
        sudo apt-get remove landscape-common
        git config --global user.name "ZyCromerZ"
        git config --global user.email "neetroid97@gmail.com"         
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
        sudo -E apt-get clean

    - name: Compile Clang
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        sudo bash ci.sh deps
        bash clang-builder.sh :v